version: 2

# Project-wide configuration
project_name: guardrail

# Hooks that run before the build
before:
  hooks:
    - go mod tidy
    - go generate ./...

# Git configuration
git:
  # What to do with commits that have the WIP prefix
  ignore_tags:
    - '^wip'

# Build metadata configuration
metadata:
  mod_timestamp: '{{ .CommitTimestamp }}'

builds:
  - id: guardrail
    main: ./cmd/guardrail
    binary: guardrail
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    # Enable reproducible builds
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath

archives:
  - id: guardrail
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: ['zip']
    files:
      - README.md
      - LICENSE
      - configs/*
    # Include SBOM in archives
    wrap_in_directory: true

# UPX compression configuration
upx:
  - enabled: true
    ids: [guardrail]
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    compress: best
    lzma: true
    brute: false

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

# Sign the checksums file
signs:
  - cmd: cosign
    certificate: '${artifact}.pem'
    output: true
    artifacts: checksum
    args:
      - sign-blob
      - '--output-certificate=${certificate}'
      - '--output-signature=${signature}'
      - '${artifact}'
      - '--yes' # Skip confirmation prompts

# SBOM generation
sboms:
  - artifacts: archive
    id: archive-sbom
    documents:
      - "${artifact}.archive.spdx.json"
    args: ["$artifact", "--file", "$document", "--output", "spdx-json"]

# Report binary sizes
report_sizes: true

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: Bug Fixes
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Improvements
      regexp: "^.*perf[(\\w)]*:+.*$"
      order: 2
    - title: Others
      order: 999

# brews:
#   - repository:
#       owner: coolguy1771
#       name: homebrew-tap
#     name: guardrail
#     homepage: "https://github.com/coolguy1771/guardrail"
#     description: "Kubernetes RBAC validation tool"
#     license: "Apache-2.0"
#     test: |
#       system "#{bin}/guardrail", "--version"
#     dependencies:
#       - name: kubectl
#         type: optional

dockers:
  - image_templates:
      - "ghcr.io/coolguy1771/guardrail:{{ .Tag }}-amd64"
      - "ghcr.io/coolguy1771/guardrail:latest-amd64"
    use: buildx
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    dockerfile: Dockerfile.goreleaser
    extra_files:
      - configs/guardrail.yaml

  - image_templates:
      - "ghcr.io/coolguy1771/guardrail:{{ .Tag }}-arm64"
      - "ghcr.io/coolguy1771/guardrail:latest-arm64"
    use: buildx
    goos: linux
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    dockerfile: Dockerfile.goreleaser
    extra_files:
      - configs/guardrail.yaml

docker_manifests:
  - name_template: "ghcr.io/coolguy1771/guardrail:{{ .Tag }}"
    image_templates:
      - "ghcr.io/coolguy1771/guardrail:{{ .Tag }}-amd64"
      - "ghcr.io/coolguy1771/guardrail:{{ .Tag }}-arm64"

  - name_template: "ghcr.io/coolguy1771/guardrail:latest"
    image_templates:
      - "ghcr.io/coolguy1771/guardrail:latest-amd64"
      - "ghcr.io/coolguy1771/guardrail:latest-arm64"

release:
  github:
    owner: coolguy1771
    name: guardrail
  draft: false
  prerelease: auto
  mode: append
  header: |
    ## Guardrail {{ .Tag }}

    ### What's Changed
  footer: |
    ### Security
    
    All release artifacts are:
    - Built with reproducible builds
    - Compressed with UPX for smaller binary sizes
    - Include SPDX SBOM (Software Bill of Materials)
    - Signed with cosign (checksums.txt.sig)
    
    To verify the checksums signature:
    ```bash
    cosign verify-blob checksums.txt \
      --certificate checksums.txt.pem \
      --signature checksums.txt.sig \
      --certificate-identity-regexp ".*" \
      --certificate-oidc-issuer https://github.com/login/oauth
    ```
    
    To verify build provenance attestations:
    ```bash
    gh attestation verify guardrail_Linux_x86_64.tar.gz \
      --owner coolguy1771
    ```
    
    **Full Changelog**: https://github.com/coolguy1771/guardrail/compare/{{ .PreviousTag }}...{{ .Tag }}

nfpms:
  - id: guardrail
    package_name: guardrail
    file_name_template: "{{ .ConventionalFileName }}"
    homepage: https://github.com/coolguy1771/guardrail
    description: |
      Kubernetes RBAC validation and analysis tool.
      Guardrail helps teams maintain secure, compliant RBAC configurations
      by detecting dangerous permissions and providing actionable insights.
    maintainer: Tyler Witlin <twitlin@witl.xyz>
    license: Apache-2.0
    vendor: Guardrail Project
    formats:
      - deb
      - rpm
      - apk
    section: utils
    priority: optional
    suggests:
      - kubectl
    contents:
      - src: ./configs/
        dst: /etc/guardrail/
        type: config
      - src: ./README.md
        dst: /usr/share/doc/guardrail/README.md
      - src: ./LICENSE
        dst: /usr/share/doc/guardrail/LICENSE
      - src: ./SECURITY.md
        dst: /usr/share/doc/guardrail/SECURITY.md
