name: CI
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write
  security-events: write
  checks: write

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # Detect if Go files changed to skip unnecessary runs
  changes:
    runs-on: ubuntu-latest
    outputs:
      go: ${{ steps.changed-files.outputs.go_any_changed }}
      docs: ${{ steps.changed-files.outputs.docs_any_changed }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46.0.5
        id: changed-files
        with:
          files_yaml: |
            go:
              - '**/*.go'
              - 'go.mod'
              - 'go.sum'
              - '.github/workflows/go-*.yml'
              - '.github/workflows/ci.yml'
            docs:
              - '**/*.md'
              - 'docs/**'

  # Lint and test Go code
  lint-test:
    needs: changes
    if: needs.changes.outputs.go == 'true'
    uses: ./.github/workflows/go-lint-test.yml
    with:
      go-version: "1.24"

  # Build binaries for multiple platforms
  build:
    needs: [changes, lint-test]
    if: needs.changes.outputs.go == 'true'
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platforms: "linux/amd64,linux/arm64"
          - os: macos-latest
            platforms: "darwin/amd64,darwin/arm64"
          - os: windows-latest
            platforms: "windows/amd64"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: "1.24"
          cache: true
      
      - name: Build for ${{ matrix.platforms }}
        shell: bash
        run: make build-cross PLATFORMS="${{ matrix.platforms }}"
      
      - name: Upload artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: guardrail-${{ matrix.os }}
          path: build/*
          retention-days: 7

  # Security scanning (CodeQL only - other tools run in lint job)
  security-scan:
    needs: changes
    if: needs.changes.outputs.go == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: "1.24"
          cache: true

      # Run CodeQL (unique to this job)
      - name: Initialize CodeQL
        uses: github/codeql-action/init@3599b3baa15b485a2e49ef411a7a4bb2452e7f93 # v3
        with:
          languages: go

      - name: Autobuild
        uses: github/codeql-action/autobuild@3599b3baa15b485a2e49ef411a7a4bb2452e7f93 # v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@3599b3baa15b485a2e49ef411a7a4bb2452e7f93 # v3
        with:
          category: "/language:go"

  # Upload coverage and artifacts
  coverage-report:
    needs: lint-test
    if: always() && needs.lint-test.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Download coverage artifact
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          name: coverage-report
          path: ./

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fdcc8476540edceab3de004e990f80d881c6cc00 # v5.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.out
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: "1.24"
          cache: true

      - name: Install gocover-cobertura
        run: go install github.com/boumenot/gocover-cobertura@latest

      - name: Convert coverage to Cobertura format
        run: gocover-cobertura < coverage.out > coverage.xml

      - name: Generate coverage badge
        uses: 5monkeys/cobertura-action@ee5787cc56634acddedc51f21c7947985531e6eb # v14
        with:
          path: coverage.xml
          minimum_coverage: 70
          fail_below_threshold: false
          show_line: true
          show_branch: true
          show_missing: true

      - name: Comment coverage on PR
        if: github.event_name == 'pull_request'
        uses: 5monkeys/cobertura-action@ee5787cc56634acddedc51f21c7947985531e6eb # v14
        with:
          path: coverage.xml
          minimum_coverage: 70
          fail_below_threshold: false
          show_line: true
          show_branch: true
          pull_request_number: ${{ github.event.pull_request.number }}
          only_changed_files: true


  # Final status check
  ci-status:
    if: always()
    needs: [lint-test, build, security-scan]
    runs-on: ubuntu-latest
    steps:
      - name: Check CI Status
        run: |
          echo "Lint/Test: ${{ needs.lint-test.result }}"
          echo "Build: ${{ needs.build.result }}"
          echo "Security: ${{ needs.security-scan.result }}"

          if [[ "${{ needs.lint-test.result }}" == "failure" || \
                "${{ needs.build.result }}" == "failure" || \
                "${{ needs.security-scan.result }}" == "failure" ]]; then
            echo "❌ CI failed"
            exit 1
          fi
          echo "✅ CI passed"
