---
name: Go Lint & Test
on:
  workflow_call:
    inputs:
      go-version:
        required: true
        type: string

env:
  GO_VERSION: ${{ inputs.go-version }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-go@v5.2.0
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/cache@v4.2.0
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-mod-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --timeout=5m

  test:
    needs: lint
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-go@v5.2.0
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Run tests with coverage
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            make test-coverage
          else
            make test
          fi

      - name: Upload coverage artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4.6.2
        with:
          name: coverage-report
          path: coverage.out
          retention-days: 1

      - name: Check coverage threshold
        if: matrix.os == 'ubuntu-latest'
        uses: vladopajic/go-test-coverage@v2.10.2
        with:
          profile: coverage.out
          local-prefix: github.com/${{ github.repository }}
          threshold-file: 70
          threshold-package: 70
          threshold-total: 70
