name: "Pull Request Labeler"
on:
  - pull_request_target

permissions:
  contents: read
  pull-requests: write

jobs:
  labeler:
    name: Label PRs
    runs-on: ubuntu-latest
    steps:
      - name: Label PR
        uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml
          sync-labels: true