name: "Pull Request Labeler"
on:
  - pull_request_target

permissions:
  contents: read
  pull-requests: write

jobs:
  labeler:
    name: Label PRs
    runs-on: ubuntu-latest
    steps:
      - name: Label PR
        uses: actions/labeler@v5.0.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
